# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chiesa Evangelica Siloe
email: ufficio@chiesasiloe.it
description: Il Gospel Forum Cosenza è una chiesa cristiana moderna ed interculturale. Centinaia di persone frequentano le varie attività e i culti domenicali oppure seguono la diretta su Facebook. Gli incontri domenicali sono un Importante punto di riferimento e attirano persone dell’intero cosentino.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chiesasiloe.it" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /:title/

paginate: 3
paginate_path: "/agenda/pagina-:num/"

collections:
  slideshow:
    output: true

plugins:
 - jekyll-paginate
 #- jekyll-sitemap
